cn:
  com:
    vortexa:
      nameserver:
        registryCenterUrl: ws://localhost:18848
        nio-thread-count: 1
        service-offline-ttl: 60
        service-instance:
          host: localhost
          port: 20001
          group: test1
          serviceId: client
          clientId: client-1
