
spring:
  datasource:
    #    url: "jdbc:sqlite://D://workspace//Vortexa-dev_3.0//vortexa-platform//src//main//resources//plantform.db"
    #    url: "jdbc:sqlite://Users/helei/develop/ideaworkspace/BotFramework/botData/db/test_plantfrom.db"
    url: jdbc:mysql://localhost:3306/vortexa_plantform
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  quartz:
    job-store-type: jdbc
    jdbc:
      table-prefix: QRTZ_
      driver-class: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/job_store
      user: root
      password: 123456
      scheduler:
        instance-name: QuartzScheduler


logging:
  level:
    org:
      apache:
        dubbo: WARN
        zookeeper: WARN
server:
  port: 10110


vortexa:
  control-server:
    nio-thread-count: 1 # netty nio 线程数
    service-offline-ttl: 120  # 服务下线时间
    service-instance:
      host: localhost # 命名服务host
      port: 18848 # 命名服务port
      group: test1
      serviceId: nameserver
      instanceId: nameserver-1
