spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vortexa_platform
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: helei
    password: 123456
  quartz:
    job-store-type: jdbc
    jdbc:
      table-prefix: QRTZ_
      driver-class: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/job_store
      user: helei
      password: 123456
      scheduler:
        instance-name: QuartzScheduler


logging:
  level:
    org:
      apache:
        dubbo: WARN
        zookeeper: WARN
server:
  port: 10110


vortexa:
  control-server:
    nio-thread-count: 1 # netty nio 线程数
    service-offline-ttl: 120  # 服务下线时间
    service-instance:
      host: localhost # 命名服务host
      port: 18848 # 命名服务port
      groupId: test1
      serviceId: nameserver
      instanceId: nameserver-1
