spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url:
    username:
    password:
  quartz:
    job-store-type: jdbc
    jdbc:
      table-prefix: QRTZ_
      driver-class: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/job_store
      user: root
      password: 123456
      scheduler:
        instance-name: QuartzScheduler

vortexa:
  botKey: stork_test
  script-agent:
    registryCenterUrl: ws://localhost:18848
    nio-thread-count: 1
    service-offline-ttl: 60
    service-instance:
      host: localhost
      port: 20002
