spring:
  main:
    banner-mode: OFF
  datasource:
    driver-class-name: org.sqlite.JDBC
    url:
    username:
    password:


vortexa:
  script-node:
    bot-group: test1
  script-agent:
    registryCenterUrl: ws://localhost:18848
    nio-thread-count: 1
    service-offline-ttl: 60
    service-instance:
      host: localhost
      port: 20001
      group: test1
      serviceId: client
      instanceId: client-1

