mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org:
      apache:
        dubbo: WARN
        zookeeper: WARN

vortexa:
  script-node:
    node-id: test1
    service-instance:
      host: localhost
      port: 20001
      group: test1
      serviceId: client
      instanceId: client-1

  botKey: ''
  filePathConfig:
    proxyFileBotConfigPath: "proxy.xlsx"
    browserEnvFileBotConfigPath: "browser_env.xlsx"
    twitterFileBotConfigPath: "twitter_account.xlsx"
    discordFileBotConfigPathL: "discord_account.xlsx"
    telegramFileBotConfigPath: "telegram_account.xlsx"
    baseAccountFileBotConfigPath: "base_account.xlsx"
  accountConfig:
    configFilePath: ""
  script-agent:
    registryCenterUrl: ws://localhost:18848
    nio-thread-count: 1
    service-offline-ttl: 60
    service-instance:
      host: localhost
      port: 20001
      group: test1
      serviceId: client
      instanceId: client-1

spring:
  main:
    banner-mode: OFF
