cn:
  com:
    vortexa:
      nameserver:
        nio-thread-count: 1
        service-offline-ttl: 120
        service-instance:
          host: localhost
          port: 18848
          group: test1
          serviceId: nameserver
          instanceId: nameserver-1
