cn:
  com:
    helei:
      nameserver:
        nio-thread-count: 1
        service-offline-ttl: 60
        service-instance:
          host: localhost
          port: 18848
          group: test1
          serviceId: nameserver
          clientId: nameserver-1
